# Site settings
title: DsixTools
tagline: The Effective Field Theory Toolkit
email: dsixtools.github@gmail.com
description: > 
  DsixTools - The Effective Field Theory Toolkit
baseurl: ""
url: "https://dsixtools.github.io/"
twitter_username: 
github_username:  dsixtools
use_math: true

# Build settings
markdown: kramdown

